Added lesson_6
KVadim7/python_homework pull request #5
Opened 2023-03-22 10:35 UTC by KVadim7

2023-03-24 10:03 UTC, desireoftheother requested changes

2023-03-24 10:03 UTC, desireoftheother commented on lesson_6/task_3.py
> +
Забагато порожніх рядків)) Можеш видалити)

2023-03-24 10:03 UTC, desireoftheother commented on lesson_6/task_2.py
> +    if list_1[index] in list_2 and not list_1[index] in common_list:
Це неправильне рішення для цієї постановки задачі. Перечитай уважніше + ми розбирали цю задачу на одному з занять.

2023-03-24 10:30 UTC, KVadim7 commented on lesson_6/task_2.py
> +    if list_1[index] in list_2 and not list_1[index] in common_list:
А що саме не так? Я здаєтья все зробив так, як ми розбирали на занятті!

2023-03-31 10:07 UTC, desireoftheother approved these changes

2023-03-31 10:07 UTC, desireoftheother commented on lesson_6/task_2.py
> +    if list_1[index] in list_2 and not list_1[index] in common_list:
Ок, сорі, моя помилка. Все ок.

2023-03-31 10:14 UTC, merged